name: thanosgalis.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26812
title: thanosgalis the voice4u
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#b16c21'
    - '#677da2'
    - '#d42c4d'
  brandStrength: 0.9747667682822794
  lightness: 0.12548121344298124
  saturation: 0.5467726453207433
  rhythmicContrast: 0
purpose: []
