name: thanosgalis.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73898
title: voice4u
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b3b3b3'
    - '#8b8b8b'
    - '#5f5f5f'
    - '#1e1e1e'
  brandStrength: 0.9747667682822794
  lightness: 0.12548121344298124
  saturation: 0.5467726453207433
  rhythmicContrast: 0.2649589020293206
purpose: []
